# Generated by Django 4.1.5 on 2023-01-08 23:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropyacht_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='show',
            unique_together={('movie', 'screen', 'end_time')},
        ),
    ]
