# Generated by Django 4.1.5 on 2023-01-08 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropyacht_app', '0002_alter_show_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
